#!/usr/bin/env zsh

local bookmark_name="$1"
local bookmark; bookmark=$(grep -E "\|${bookmark_name}$" "$BOOKMARKS_FILE" 2>/dev/null)

if [[ -z "$bookmark" ]] ; then
  @bookmarks_usage
  return 1
else
  local dir="${bookmark%%|*}"
  echo "$bookmark_name" > "$BOOKMARKS_LAST"
  builtin cd ${dir//\~/$HOME}
fi
